name: This workflow is a demo for reusable workflows

on:
  push:
    branches:
      - main
  workflow_call: # allows this workflow to be called by other workflows
    inputs:
      NAMESPACE:
        required: true
        type: string
      IMAGE_NAME:
        required: true
        type: string
    secrets:
      KUBECONFIG:
        description: 'Kubeconfig for Kubernetes Cluster'
        required: true
  pull_request:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to Kubernetes
    runs-on: self-hosted
    env:
      NAMESPACE: ${{ inputs.NAMESPACE }}
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Install kubectl
        run: |
          # 1. Detect system architecture
          ARCH=$(uname -m)
          if [ "$ARCH" = "x86_64" ]; then
              ARCH="amd64"
          elif [ "$ARCH" = "aarch64" ]; then
              ARCH="arm64"
          fi
          
          
          # 2. Get the actual stable version string (Notice the dl.k8s.io domain)
          VERSION="v1.34.0"
          
          # 3. Download using the correct URL format (Notice the $ and the /)
          curl -LO "https://dl.k8s.io/release/${VERSION}/bin/linux/${ARCH}/kubectl"
          
          # 4. Install and verify
          chmod +x ./kubectl
          sudo mv ./kubectl /usr/local/bin/kubectl
          kubectl version --client
      - name: Configure Kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG }}" > ~/.kube/config
          kubectl version
          kubectl get nodes
      - name: Install yq
        run: |
          # 1. Detect system architecture
          ARCH=$(uname -m)
          if [ "$ARCH" = "x86_64" ]; then
              ARCH="amd64"
          elif [ "$ARCH" = "aarch64" ]; then
              ARCH="arm64"
          fi
          sudo curl -L https://github.com/mikefarah/yq/releases/latest/download/yq_linux_${ARCH} -o /usr/local/bin/yq
          sudo chmod +x /usr/local/bin/yq
          yq --version
      - name: update image name in deployment YAML
        run: |
          IMAGE_TAGS="${{ github.run_id}}-${GITHUB_SHA::7}"
          export IMAGE="${{ inputs.IMAGE_NAME }}:${IMAGE_TAGS}"
          yq e '.spec.template.spec.containers[0].image = strenv(IMAGE)' manifests/deployment.yaml -i
          cat manifests/deployment.yaml
      - name: Create Namesapace if not exists
        run: |
          kubectl get namespace $NAMESPACE || kubectl create namespace $NAMESPACE
      - name: Deploy to Kubernetes Cluster
        run: |
          kubectl apply -f manifests/ -n $NAMESPACE
      - name: verify deployment
        run: |
          kubectl rollout status deployment/thinknyxapp -n $NAMESPACE
          kubectl get all -n $NAMESPACE
